'use client';

import { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'tr' | 'en';

const tr = {
    changeFile: 'Dosya değiştir',
    settings: 'Ayarlar',
    courses: 'ders',
    ects: 'ECTS',
    createSchedule: 'Program oluştur',
    creating: 'Oluşturuluyor...',
    searchCourse: 'Ders ara...',
    coursesSelected: 'ders seçildi',
    noFileUploaded: 'Henüz dosya yüklenmedi',
    uploadFile: 'Dosya yükle',
    allSectionsLocked: 'Tüm şubeler kilitli',
    weeklySchedule: 'Haftalık program',
    program: 'Program',
    time: 'Saat',
    mon: 'Pzt',
    tue: 'Sal',
    wed: 'Çar',
    thu: 'Per',
    fri: 'Cum',
    uploadTitle: 'Ders programını yükle',
    uploadSubtitle: 'Yalnızca .xlsx uzantılı Excel dosyasını sürükle veya seç',
    uploading: 'Yükleniyor...',
    selectFile: 'Dosya seç',
    continue: 'Devam et',
    uploadInvalidFile: 'Lütfen yalnızca .xlsx uzantılı Excel dosyası yükleyin.',
    uploadFailed: 'Dosya yüklenirken bir hata oluştu. Backend çalışıyor mu?',
    uploadDropTitle: 'Excel dosyanızı buraya sürükleyin',
    uploadDropOr: 'veya',
    uploadRemoveFile: 'Dosyayı kaldır',
    uploadSubmit: 'Yükle ve programı aç',
    uploadSuccessTitle: 'Yükleme başarılı',
    uploadFileLabel: 'Dosya',
    uploadCourseCountLabel: 'Ders sayısı',
    uploadRedirecting: 'Program açılıyor...',
    uploadContinueToScheduler: 'Programa geç',
    homeLogin: 'Giriş',
    homeStart: 'Başla',
    homeBadge: 'Işık Üniversitesi öğrencileri için tasarlandı',
    homeTitleLine1: 'Ders Programını',
    homeTitleLine2: 'Saniyeler İçinde Oluştur',
    homeDescription: 'Derslerini seç; ECTS limitini, çakışma toleransını ve istemediğin saatleri ayarla. Planlayıcı uygun program seçeneklerini oluştursun.',
    homeVisualAlt: 'Akıllı ders programı oluşturma sürecini gösteren haftalık takvim illüstrasyonu',
    homePrimaryCta: 'Hemen Başla',
    homeSecondaryCta: 'Excel Yükle',
    homeFeaturesEyebrow: 'Özellikler',
    homeFeaturesTitle: 'Neden IşıkSchedule?',
    homeFeatureFastTitle: 'Hızlı Program Üretimi',
    homeFeatureFastDescription: 'Ders seçeneklerini saniyeler içinde tarayıp kullanılabilir program kombinasyonlarını çıkar.',
    homeFeatureOptimizeTitle: 'Esnek Tercihler',
    homeFeatureOptimizeDescription: 'ECTS limitini ve çakışma toleransını ayarla; istemediğin saatleri kilitle ve uygun şubeyi seç.',
    homeFeatureExportTitle: 'Kolay Dışa Aktarım',
    homeFeatureExportDescription: 'Programını iCal olarak indir, PDF için yazdır veya paylaşılabilir link oluştur.',
    homeStepsEyebrow: 'Adımlar',
    homeStepsTitle: 'Nasıl Çalışır?',
    homeStepUploadTitle: 'Yükle',
    homeStepUploadDescription: 'Excel formatındaki ders listesini yükle veya aktif global dönemi kullan.',
    homeStepSelectTitle: 'Seç',
    homeStepSelectDescription: 'Derslerini seç; ECTS limitini, çakışma toleransını ve kilitli saatleri ayarla.',
    homeStepGenerateTitle: 'Oluştur',
    homeStepGenerateDescription: 'Planlayıcı uygun şube kombinasyonlarını otomatik olarak oluştursun.',
    homeFooterText: 'Işık Üniversitesi öğrencileri için geliştirilmiş bağımsız bir öğrenci projesidir.',
    homePreviewLive: 'Canlı Önizleme',
    homeStatScore: 'Skor',
    homeStatEcts: 'Toplam ECTS',
    loginProductSubtitle: 'Ders Programı Oluşturucu',
    loginTitle: 'Giriş Yap',
    loginEmailLabel: 'E-posta',
    loginPasswordLabel: 'Şifre',
    loginSubmit: 'Giriş Yap',
    loginSubmitting: 'Giriş yapılıyor...',
    loginNoAccount: 'Hesabınız yok mu?',
    loginRegisterLink: 'Kayıt Ol',
    loginDomainNote: 'Sadece @isik.edu.tr ve @isikun.edu.tr e-postaları kabul edilir',
    loginFailed: 'Giriş başarısız',
    showPassword: 'Şifreyi göster',
    hidePassword: 'Şifreyi gizle',
    registerProductSubtitle: 'Hesap Oluştur',
    registerTitle: 'Kayıt Ol',
    registerEmailLabel: 'E-posta',
    registerEmailHint: '@isik.edu.tr veya @isikun.edu.tr',
    registerPasswordLabel: 'Şifre',
    registerConfirmLabel: 'Şifre Tekrar',
    registerSubmit: 'Kayıt Ol',
    registerSubmitting: 'Kayıt yapılıyor...',
    registerHaveAccount: 'Zaten hesabınız var mı?',
    registerLoginLink: 'Giriş Yap',
    registerPasswordMismatch: 'Şifreler eşleşmiyor',
    registerPasswordTooShort: 'Şifre en az 6 karakter olmalı',
    registerInvalidDomain: 'E-posta @isik.edu.tr veya @isikun.edu.tr olmalı',
    registerFailed: 'Kayıt başarısız',
    settingsTitle: 'Ayarlar',
    tools: 'Araçlar',
    openTools: 'Planlama araçlarını aç',
    openNavigation: 'Navigasyon menüsünü aç',
    generateShort: 'Oluştur',
    schedulerRegenerate: 'Yeniden oluştur',
    maxEcts: 'Maksimum ECTS',
    conflictTolerance: 'Çakışma toleransı',
    lecture: 'Ders',
    lab: 'Lab',
    problemSession: 'PS',
    teacher: 'Öğretim üyesi',
    schedule: 'Saatler',
    switchSection: 'Şube değiştir',
    removeCourse: 'Dersi kaldır',
    pleaseSelectCourse: 'Lütfen önce ders seçin.',
    courseCannotBeAdded: 'eklenemiyor.',
    allSectionsConflict: 'Tüm şubeler kilitli saatlerle çakışıyor.',
    solutionRemoveLocks: 'Bazı kilitleri kaldırın veya farklı bir ders seçin.',
    sectionConflictsWithLock: 'Bu şube kilitli saatlerle çakışıyor.',
    locked: 'kilitlendi',
    sectionChanged: 'Şube değiştirildi',
    removedNoAlternative: 'Alternatif bulunamadığı için kaldırıldı',
    toReaddRemoveLocks: 'Bu dersleri tekrar eklemek için kilitleri kaldırın',
    backendConflict: 'Oluşturulan programlar kilitlerle çakışıyor. Mevcut seçim korunuyor.',
    generationFailed: 'Oluşturma başarısız',
    unknownError: 'Bilinmeyen hata',
    unlock: 'Kilidi kaldır',
    lock: 'Kilitle',
    loadingCourses: 'Ders verileri yükleniyor...',
    activeSource: 'Kaynak',
    allCoursesLabel: 'Tümü',
    selectedOnly: 'Seçili',
    blockedOnly: 'Kilitli',
    codeGroup: 'Kod grubu',
    allCodeGroups: 'Tüm kod grupları',
    academicUnit: 'Akademik birim',
    allAcademicUnits: 'Tüm akademik birimler',
    noSearchResults: 'Aramana uyan ders bulunamadı.',
    resetFilters: 'Filtreleri sıfırla',
    clearLocks: 'Kilitleri temizle',
    clearSelection: 'Seçimi temizle',
    quickTips: 'Hızlı ipuçları',
    tipSelectCourses: 'Soldan ders ekleyip çıkararak taslak programını oluştur.',
    tipLockSlots: 'Boş hücreleri sürükleyerek meşgul saatlerini işaretle; kilit ikonuyla tek tek de kapatabilirsin.',
    tipCreateAlternatives: 'Hazır olduğunda program oluşturup alternatifleri gez.',
    manualDraft: 'Manuel taslak görünümü',
    generatedOptions: 'oluşturulan alternatif',
    conflictsLabel: 'çakışma',
    resultsHeading: 'Oluşturulan Programlar',
    resultsAlternatives: 'alternatif',
    resultsBackToScheduler: 'Programa dön',
    resultsEyebrowPre: 'Planlayıcı senin için ',
    resultsEyebrowPost: ' uygun kombinasyon hazırladı',
    resultsTitlePre: 'Sana en uygun ',
    resultsTitleHighlight: 'haftalık programı',
    resultsTitlePost: ' seç',
    resultsSubtitle: 'Skor, ECTS ve çakışmaya göre sıralandı. Favorile, karşılaştır ve hazır olduğunda seç.',
    resultsSingleEyebrow: 'Planlayıcı senin için tek uygun kombinasyon hazırladı',
    resultsSinglePre: 'Sana uyan ',
    resultsSingleHighlight: 'tek program',
    resultsSinglePost: ' hazır',
    resultsSingleSubtitle: 'Seçtiğin dersler ve tercihlerle oluşturulabilen tek program bu. İncele, takvime aktar veya paylaş.',
    resultsEmptyTitle: 'Uygun program bulunamadı',
    resultsEmptySubtitle: 'Seçtiğin dersler ve tercihlerle çakışmasız bir program oluşturulamadı. Derslerini ya da tercihlerini (ECTS limiti, çakışma toleransı, kilitli saatler) gözden geçirip yeniden dene.',
    resultsEmptyAction: 'Dersleri ve tercihleri düzenle',
    resultsVariantsTitle: 'Aynı saat düzeni',
    resultsVariantsShort: 'seçenek',
    resultsVariantsShownNote: '{total} seçenekten {shown} tanesi gösteriliyor',
    diagReasonsTitle: 'Olası sebepler',
    diagMissingCourse: '{course} dersi bu kaynakta bulunamadı.',
    diagMissingComponent: '{course} dersinin gerekli {type} bileşeni eksik.',
    diagLockedBlocks: 'Kilitlediğin saatler {course} dersinin tüm şubelerini engelliyor.',
    diagEctsExceeded: 'ECTS limitin {limit}, ama en az {min} gerekli.',
    diagConflictExceeded: 'Çakışma toleransın ({limit}) içinde uygun program kurulamıyor.',
    resultsBestMatch: 'En iyi eşleşme',
    resultsArchetypeCompact: 'En kompakt',
    resultsArchetypeFreeDays: 'En çok boş gün',
    resultsArchetypeLateStart: 'Geç başlayan',
    resultsArchetypeLight: 'En hafif',
    resultsNoConflict: 'Çakışmasız',
    resultsFreeDaysLabel: 'Boş gün',
    resultsScoreBreakdown: 'Puan dağılımı',
    resultsStatCourses: 'Ders',
    resultsTimeColumn: 'Saat',
    resultsSelect: 'Seç',
    resultsSelected: 'Seçildi',
    resultsCompare: 'Karşılaştır',
    resultsCompareHint: 'Karşılaştırmak için 2 veya 3 program seç',
    resultsCompareLimit: 'En fazla 3 program karşılaştırabilirsin',
    resultsCompareView: 'Karşılaştırma',
    resultsCompareSubtitle: 'Programların günlük düzenini ve temel metriklerini yan yana incele.',
    resultsCompareSchedule: 'Metrik',
    resultsCompareScore: 'Skor',
    resultsCompareConflicts: 'Çakışma',
    resultsCompareFreeDays: 'Boş gün',
    resultsCompareGaps: 'Toplam ara',
    resultsCompareHoursUnit: 'saat',
    resultsCompareFirstClass: 'İlk ders',
    resultsCompareLastClass: 'Son ders',
    resultsCompareBusiestDay: 'En yoğun gün',
    resultsCompareClassHours: 'Ders saati',
    resultsCompareNone: 'Yok',
    resultsWhyTitle: 'Neden bu program?',
    resultsWhySubtitle: 'Skorun nasıl oluştuğunu ve haftanın günlük yaşamına nasıl yansıdığını birlikte gör.',
    resultsWhyCourses: '{count} dersin tamamı yerleştirildi.',
    resultsWhyNoConflict: 'Dersler arasında saat çakışması yok.',
    resultsWhyHasConflicts: 'Programda {count} saat çakışması bulunuyor.',
    resultsWhyFreeDays: '{days} boş bırakıldı.',
    resultsWhyNoFreeDays: 'Hafta içi her gün en az bir ders var.',
    resultsWhyGaps: 'Hafta boyunca toplam {count} saat ara var.',
    resultsWhyHours: 'Toplam {count} ders saati; ilk ders {first}, son ders {last}.',
    resultsSearchIncomplete: 'Bu seçim, bulunan ilk {count} uygun düzen arasından kalite ve çeşitlilik dengelenerek hazırlandı; tüm çözüm uzayı taranmadı.',
    resultsFavorite: 'Favori',
    resultsShareableEyebrow: 'Paylaşılabilir kart',
    resultsShareableTitle: 'Ekran görüntüsü almaya değer',
    resultsTotalScore: 'Toplam skor',
    scoreInfoTitle: 'Skor nasıl hesaplanıyor?',
    scoreInfoIntro: 'Skor, programın kalitesini 100 üzerinden gösterir. Şu bileşenlerin toplamıdır:',
    scoreInfoConflictLabel: 'Çakışmasızlık',
    scoreInfoConflictTip: 'Çakışma, iki dersin aynı gün ve saatte denk gelmesidir. 0 çakışma 35 puan verir; her çakışma 12 puan düşürür (en az 0).',
    scoreInfoCoverageLabel: 'Ders kapsamı',
    scoreInfoCoverageTip: 'Seçilen tüm dersleri eksiksiz içeren her geçerli program 25 puan alır.',
    scoreInfoEctsLabel: 'ECTS toplamı',
    scoreInfoEctsTip: 'Avrupa Kredi Transfer Sistemi kredisi. Skoru etkilemez; bilgi olarak ayrıca gösterilir.',
    scoreInfoFreeDaysTermLabel: 'Boş gün bonusu',
    scoreInfoFreeDaysTip: 'Tamamen boş her hafta içi gün +7 puan ekler (en çok 20) — daha çok boş gün daha yüksek skor.',
    scoreInfoGapsLabel: 'Kompaktlık',
    scoreInfoGapsTip: 'En çok 20 puan; gün içindeki her boş ara saat 4 puan düşürür — daha sıkışık (boşluksuz) program daha yüksek skor.',
    scoreInfoTotal: 'Toplam skor',
    scoreInfoFootnote: 'Skor 100 üzerindendir: çakışmasız, boş günü çok ve daha az boşluk içeren programlar daha yüksek puan alır.',
    scoreInfoHoldHint: 'Sabitlemek için bekle',
    scoreInfoLockedHint: 'Sabitlendi — terimlerin üstüne gel',
    scoreInfoClose: 'Kapat',
    resultsPhoneTitle: 'Telefonuna aktar',
    resultsPhoneDesc: 'QR kodu okut, programını her yerde yanında taşı.',
    resultsExportIcs: 'Takvime aktar (.ics)',
    resultsPrintPdf: 'Yazdır / PDF',
    resultsShare: 'Programı paylaş',
    resultsCopy: 'Bağlantıyı kopyala',
    resultsCopied: 'Bağlantı kopyalandı',
    resultsViewAll: 'Programları gör',
    pickCoursesHint: 'Başlamak için ders seç.',
    restoredSession: 'Son çalışma durumun geri yüklendi.',
    selectionReset: 'Seçili dersler temizlendi.',
    locksReset: 'Tüm kilitler kaldırıldı.',
    selectionMayConflict: 'Seçilen şube mevcut programla çakışabilir.',
    unavailableCoursesSkipped: 'Bazı eski seçimler yeni veri kaynağında bulunamadı.',
    prerequisiteWarning: 'Seçilen dersin bazı önkoşulları programında eksik:',
    corequisiteWarning: 'Seçilen dersin bazı eşkoşulları programında bulunmuyor:',
    missingPreCoWarning: 'Eksik Önkoşul/Eşkoşul Uyarıları',
    undo: 'Geri al',
    redo: 'Yinele',
    nothingToUndo: 'Geri alınacak işlem yok.',
    nothingToRedo: 'Yinelenecek işlem yok.',
    undone: 'Son işlem geri alındı.',
    redone: 'İşlem yinelendi.',
    exportMenu: 'Dışa aktar',
    exportIcal: 'Takvime aktar (.ics)',
    exportPrint: 'Yazdır / PDF',
    exportIcalDone: 'Takvim dosyası hazır.',
    exportNothingToExport: 'Dışa aktarılacak ders yok.',
    instructor: 'Öğretim üyesi',
    allInstructors: 'Tüm öğretim üyeleri',
    clearSearch: 'Aramayı temizle',
    stats: 'İstatistikler',
    statsFreeDays: 'Boş günler',
    statsFreeDay: 'Boş gün',
    statsBusyDays: 'Dolu günler',
    statsTotalHours: 'Toplam ders saati',
    statsGaps: 'Ara saat',
    statsFirstClass: 'İlk ders',
    statsLastClass: 'Son ders',
    statsNoClass: 'Ders yok',
    confirmClearSelectionTitle: 'Tüm seçimleri temizle?',
    confirmClearSelectionMessage: 'Seçili tüm dersler programından kaldırılacak.',
    confirmClearLocksTitle: 'Tüm kilitleri kaldır?',
    confirmClearLocksMessage: 'İşaretli saat kilitlerinin hepsi silinecek.',
    confirmYes: 'Evet, devam et',
    confirmCancel: 'Vazgeç',
    keyboardShortcuts: 'Klavye kısayolları',
    shortcutUndo: 'Son işlemi geri al',
    shortcutRedo: 'İşlemi yinele',
    shortcutPrevSchedule: 'Önceki program',
    shortcutNextSchedule: 'Sonraki program',
    shortcutGenerate: 'Program oluştur',
    shortcutToggleHelp: 'Bu pencereyi aç/kapat',
    shortcutCloseModal: 'Açık pencereyi kapat',
    shortcutFocusSearch: 'Aramaya odaklan',
    shortcutExport: 'Dışa aktarma menüsü',
    navScheduler: 'Program',
    navUpload: 'Yükle',
    navAdmin: 'Admin',
    navLogin: 'Giriş',
    navLogout: 'Çıkış Yap',
    close: 'Kapat',
    closeDialog: 'Pencereyi kapat',
    redirectTitle: 'Programa yönlendiriliyor',
    redirectDescription: 'Bu eski akış artık ana program oluşturucuya taşındı.',
    schedulerNoActiveTitle: 'Aktif dönem bulunamadı',
    schedulerNoActiveDescription: 'Henüz global ders dönemi tanımlı değil. Devam etmek için .xlsx ders dosyanı yükleyebilirsin.',
    schedulerOpenCourseDrawer: 'Dersler',
    schedulerCoursesDrawerTitle: 'Dersler',
    schedulerMobileDaySchedule: 'Günlük program',
    schedulerNoCoursesForDay: 'Bu gün için ders yok.',
    schedulerEmptySlot: 'Boş saat',
    schedulerPreferences: 'Tercihler',
    schedulerEarliest: 'En erken ders',
    schedulerLatest: 'En geç ders',
    schedulerDaysOff: 'Boş istenen günler',
    schedulerGapPref: 'Boşluk tercihi',
    schedulerGapCompact: 'Sıkışık',
    schedulerGapBalanced: 'Dengeli',
    schedulerGapSpread: 'Seyrek',
    schedulerSelectedTitle: 'Seçilen dersler',
    schedulerNoSelectionHint: 'Ders seçtikçe burada görünür.',
    schedulerCoursesTitle: 'Dersler',
    schedulerBuildTitle: 'Program',
    schedulerShowCourses: 'Ders listesini göster',
    schedulerHideCourses: 'Ders listesini gizle',
    schedulerShowBuild: 'Program panelini göster',
    schedulerHideBuild: 'Program panelini gizle',
    schedulerBlockedTimes: 'Kilitli saatler',
    schedulerNoBlockedTitle: 'Kilitli saat yok',
    schedulerNoBlockedDescription: 'Programda uygun olmayan bir saati kilitlemek için boş veya dolu hücredeki kilit düğmesini kullan.',
    schedulerUnblockTime: 'Saat kilidini kaldır',
    schedulerEctsBudget: 'ECTS bütçesi',
    schedulerEctsRemaining: 'ECTS daha ekleyebilirsin',
    schedulerEctsOver: 'ECTS limitin üzerinde',
    schedulerEctsFull: 'ECTS bütçesi doldu',
    schedulerClassWindow: 'Ders saat aralığı',
    schedulerConflictHelp: 'Program oluşturulurken izin verilen en fazla çakışan ders bloğu sayısıdır. 0 seçildiğinde hiçbir çakışmaya izin verilmez.',
    schedulerGapHelp: 'Dersler arasındaki boş zamanı düzenler. Kompakt dersleri art arda toplar, Dengeli kısa molalar bırakır, Seyrek daha geniş aralıklara izin verir.',
    schedulerShareSchedule: 'Programı Paylaş',
    schedulerShareAction: 'Programı Paylaş (Link & QR)',
    schedulerShareDescription: 'Bu QR kodu okutarak veya aşağıdaki linki kullanarak paylaştığınız programa erişebilirsiniz.',
    schedulerCopyLink: 'Kopyala',
    schedulerShareCopied: 'Link kopyalandı.',
    schedulerShareFailed: 'Program paylaşılamadı.',
    schedulerShareCodeFailed: 'Kod oluşturulamadı.',
    schedulerGeneratedCount: 'program oluşturuldu.',
    schedulerSelectedAlternative: 'Seçili',
    adminPanel: 'Admin Paneli',
    adminRole: 'ADMIN',
    adminNewSemester: 'Yeni Dönem Yükle',
    adminNewSemesterDesc: 'Excel dosyasını yükleyerek tüm kullanıcılara sunun.',
    adminSemesterName: 'Dönem Adı',
    adminExcelFile: 'Excel Dosyası',
    adminChooseExcel: 'Excel Seç',
    adminUploading: 'Yükleniyor...',
    adminSemesters: 'Yüklenen Dönemler',
    adminNoSemesters: 'Henüz dönem yüklenmedi.',
    adminActivate: 'Aktif Yap',
    adminActive: 'AKTİF',
    adminUsers: 'Kullanıcı',
    adminSavedSchedules: 'Kayıtlı Program',
    adminCourses: 'Ders',
    adminActiveSemester: 'Aktif Dönem',
    adminNone: 'Yok',
    adminUploadInvalid: 'Sadece .xlsx uzantılı Excel dosyaları yüklenebilir.',
    adminUploadSuccess: 'ders yüklendi.',
    adminUploadError: 'Yükleme hatası',
    adminActivateSuccess: 'Dönem aktif edildi.',
    adminFetchError: 'Admin verileri alınamadı.',
    adminActivateError: 'Dönem aktif edilemedi.',
    adminStatsLoading: 'İstatistikler yükleniyor...',
    adminSemestersLoading: 'Dönemler yükleniyor...',
    sharedLoading: 'Paylaşılan program yükleniyor...',
    sharedNotFoundTitle: 'Program bulunamadı',
    sharedNotFoundDescription: 'Bu paylaşılan program bulunamadı veya silinmiş olabilir.',
    sharedReturnHome: 'Anasayfaya Dön',
    sharedSchedule: 'Paylaşılan Program',
    sharedMakeOwn: 'Kendi Programını Yap',
    sharedCourseCount: 'ders',
    sharedMobileTitle: 'Günlük görünüm',
};

export type Translations = typeof tr;

const en: Translations = {
    changeFile: 'Change file',
    settings: 'Settings',
    courses: 'courses',
    ects: 'ECTS',
    createSchedule: 'Generate schedule',
    creating: 'Creating...',
    searchCourse: 'Search course...',
    coursesSelected: 'courses selected',
    noFileUploaded: 'No file uploaded yet',
    uploadFile: 'Upload file',
    allSectionsLocked: 'All sections locked',
    weeklySchedule: 'Weekly schedule',
    program: 'Schedule',
    time: 'Time',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    uploadTitle: 'Upload course schedule',
    uploadSubtitle: 'Drag and drop or select a .xlsx Excel file',
    uploading: 'Uploading...',
    selectFile: 'Select file',
    continue: 'Continue',
    uploadInvalidFile: 'Please upload a .xlsx Excel file.',
    uploadFailed: 'Something went wrong while uploading. Is the backend running?',
    uploadDropTitle: 'Drag your Excel file here',
    uploadDropOr: 'or',
    uploadRemoveFile: 'Remove file',
    uploadSubmit: 'Upload and open scheduler',
    uploadSuccessTitle: 'Upload successful',
    uploadFileLabel: 'File',
    uploadCourseCountLabel: 'Course count',
    uploadRedirecting: 'Redirecting to scheduler...',
    uploadContinueToScheduler: 'Open scheduler',
    homeLogin: 'Log in',
    homeStart: 'Start',
    homeBadge: 'Designed for Işık University students',
    homeTitleLine1: 'Build Your Course Schedule',
    homeTitleLine2: 'In Seconds',
    homeDescription: 'Pick your courses, set ECTS and conflict limits, and lock unavailable hours. The planner will generate suitable schedule options.',
    homeVisualAlt: 'Weekly calendar illustration showing intelligent course schedule generation',
    homePrimaryCta: 'Start Now',
    homeSecondaryCta: 'Upload Excel',
    homeFeaturesEyebrow: 'Features',
    homeFeaturesTitle: 'Why IşıkSchedule?',
    homeFeatureFastTitle: 'Fast Schedule Generation',
    homeFeatureFastDescription: 'Scan course options in seconds and find usable schedule combinations quickly.',
    homeFeatureOptimizeTitle: 'Flexible Preferences',
    homeFeatureOptimizeDescription: 'Set ECTS and conflict limits, lock unavailable hours, and choose the section that fits.',
    homeFeatureExportTitle: 'Easy Export',
    homeFeatureExportDescription: 'Download your schedule as iCal, print to PDF, or create a shareable link.',
    homeStepsEyebrow: 'Steps',
    homeStepsTitle: 'How It Works',
    homeStepUploadTitle: 'Upload',
    homeStepUploadDescription: 'Upload an Excel course list or use the active global semester.',
    homeStepSelectTitle: 'Select',
    homeStepSelectDescription: 'Choose courses, set ECTS and conflict limits, and mark locked hours.',
    homeStepGenerateTitle: 'Generate',
    homeStepGenerateDescription: 'Let the planner create suitable section combinations automatically.',
    homeFooterText: 'An independent student project built for Işık University students.',
    homePreviewLive: 'Live Preview',
    homeStatScore: 'Score',
    homeStatEcts: 'Total ECTS',
    loginProductSubtitle: 'Course Schedule Builder',
    loginTitle: 'Log In',
    loginEmailLabel: 'Email',
    loginPasswordLabel: 'Password',
    loginSubmit: 'Log In',
    loginSubmitting: 'Logging in...',
    loginNoAccount: 'No account yet?',
    loginRegisterLink: 'Create Account',
    loginDomainNote: 'Only @isik.edu.tr and @isikun.edu.tr emails are accepted',
    loginFailed: 'Login failed',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    registerProductSubtitle: 'Create Account',
    registerTitle: 'Sign Up',
    registerEmailLabel: 'Email',
    registerEmailHint: '@isik.edu.tr or @isikun.edu.tr',
    registerPasswordLabel: 'Password',
    registerConfirmLabel: 'Confirm Password',
    registerSubmit: 'Sign Up',
    registerSubmitting: 'Signing up...',
    registerHaveAccount: 'Already have an account?',
    registerLoginLink: 'Log In',
    registerPasswordMismatch: 'Passwords do not match',
    registerPasswordTooShort: 'Password must be at least 6 characters',
    registerInvalidDomain: 'Email must be @isik.edu.tr or @isikun.edu.tr',
    registerFailed: 'Registration failed',
    settingsTitle: 'Settings',
    tools: 'Tools',
    openTools: 'Open planning tools',
    openNavigation: 'Open navigation menu',
    generateShort: 'Generate',
    schedulerRegenerate: 'Regenerate',
    maxEcts: 'Max ECTS',
    conflictTolerance: 'Conflict tolerance',
    lecture: 'Lecture',
    lab: 'Lab',
    problemSession: 'PS',
    teacher: 'Instructor',
    schedule: 'Schedule',
    switchSection: 'Switch section',
    removeCourse: 'Remove course',
    pleaseSelectCourse: 'Please select a course first.',
    courseCannotBeAdded: 'cannot be added.',
    allSectionsConflict: 'All sections conflict with locked slots.',
    solutionRemoveLocks: 'Remove some locks or choose a different course.',
    sectionConflictsWithLock: 'This section conflicts with locked slots.',
    locked: 'locked',
    sectionChanged: 'Section changed',
    removedNoAlternative: 'Removed because no alternative was found',
    toReaddRemoveLocks: 'Remove locks to add these courses back',
    backendConflict: 'Generated schedules conflict with locked slots. Keeping your current selection.',
    generationFailed: 'Generation failed',
    unknownError: 'Unknown error',
    unlock: 'Unlock',
    lock: 'Lock',
    loadingCourses: 'Loading course data...',
    activeSource: 'Source',
    allCoursesLabel: 'All',
    selectedOnly: 'Selected',
    blockedOnly: 'Blocked',
    codeGroup: 'Code group',
    allCodeGroups: 'All code groups',
    academicUnit: 'Academic unit',
    allAcademicUnits: 'All academic units',
    noSearchResults: 'No courses match your search.',
    resetFilters: 'Reset filters',
    clearLocks: 'Clear locks',
    clearSelection: 'Clear selection',
    quickTips: 'Quick tips',
    tipSelectCourses: 'Build a draft schedule by adding and removing courses from the left.',
    tipLockSlots: 'Drag across empty cells to mark busy hours, or use the lock icon to block them one by one.',
    tipCreateAlternatives: 'When ready, generate schedules and browse the alternatives.',
    manualDraft: 'Manual draft view',
    generatedOptions: 'generated options',
    conflictsLabel: 'conflicts',
    resultsHeading: 'Generated Schedules',
    resultsAlternatives: 'alternatives',
    resultsBackToScheduler: 'Back to schedule',
    resultsEyebrowPre: 'The planner prepared ',
    resultsEyebrowPost: ' suitable combinations for you',
    resultsTitlePre: 'Pick the ',
    resultsTitleHighlight: 'weekly schedule',
    resultsTitlePost: ' that fits you best',
    resultsSubtitle: 'Sorted by score, ECTS and conflicts. Favourite, compare, and select when ready.',
    resultsSingleEyebrow: 'The planner prepared one suitable combination for you',
    resultsSinglePre: 'We found ',
    resultsSingleHighlight: 'one schedule',
    resultsSinglePost: ' that fits',
    resultsSingleSubtitle: 'This is the only schedule that fits your courses and preferences. Review it, add to calendar, or share.',
    resultsEmptyTitle: 'No suitable schedule found',
    resultsEmptySubtitle: 'No conflict-free schedule could be built from your courses and preferences. Review your courses or preferences (ECTS limit, conflict tolerance, locked hours) and try again.',
    resultsEmptyAction: 'Edit courses and preferences',
    resultsVariantsTitle: 'Same time layout',
    resultsVariantsShort: 'options',
    resultsVariantsShownNote: 'Showing {shown} of {total} options',
    diagReasonsTitle: 'Possible reasons',
    diagMissingCourse: '{course} was not found in this source.',
    diagMissingComponent: '{course} is missing its required {type} component.',
    diagLockedBlocks: 'Your locked hours block every section of {course}.',
    diagEctsExceeded: 'Your ECTS limit is {limit}, but at least {min} is required.',
    diagConflictExceeded: 'No schedule fits within your conflict tolerance ({limit}).',
    resultsBestMatch: 'Best match',
    resultsArchetypeCompact: 'Most compact',
    resultsArchetypeFreeDays: 'Most free days',
    resultsArchetypeLateStart: 'Latest start',
    resultsArchetypeLight: 'Lightest',
    resultsNoConflict: 'No conflicts',
    resultsFreeDaysLabel: 'Free days',
    resultsScoreBreakdown: 'Score breakdown',
    resultsStatCourses: 'Courses',
    resultsTimeColumn: 'Time',
    resultsSelect: 'Select',
    resultsSelected: 'Selected',
    resultsCompare: 'Compare',
    resultsCompareHint: 'Pick 2 or 3 schedules to compare',
    resultsCompareLimit: 'You can compare up to 3 schedules',
    resultsCompareView: 'Comparison',
    resultsCompareSubtitle: 'Review the daily shape and key metrics of each schedule side by side.',
    resultsCompareSchedule: 'Metric',
    resultsCompareScore: 'Score',
    resultsCompareConflicts: 'Conflicts',
    resultsCompareFreeDays: 'Free days',
    resultsCompareGaps: 'Total gaps',
    resultsCompareHoursUnit: 'hours',
    resultsCompareFirstClass: 'First class',
    resultsCompareLastClass: 'Last class',
    resultsCompareBusiestDay: 'Busiest day',
    resultsCompareClassHours: 'Class hours',
    resultsCompareNone: 'None',
    resultsWhyTitle: 'Why this schedule?',
    resultsWhySubtitle: 'See how its score is formed and what its weekly shape means in daily life.',
    resultsWhyCourses: 'All {count} courses were placed.',
    resultsWhyNoConflict: 'There are no time conflicts between classes.',
    resultsWhyHasConflicts: 'This schedule contains {count} conflicting time slots.',
    resultsWhyFreeDays: '{days} left free.',
    resultsWhyNoFreeDays: 'There is at least one class on every weekday.',
    resultsWhyGaps: 'There are {count} idle hours across the week.',
    resultsWhyHours: '{count} class hours in total; first class at {first}, last class at {last}.',
    resultsSearchIncomplete: 'This selection balances quality and variety across the first {count} suitable layouts found; the full solution space was not searched.',
    resultsFavorite: 'Favourite',
    resultsShareableEyebrow: 'Shareable card',
    resultsShareableTitle: 'Worth a screenshot',
    resultsTotalScore: 'Total score',
    scoreInfoTitle: 'How is the score calculated?',
    scoreInfoIntro: 'The score rates a schedule out of 100. It is the sum of these parts:',
    scoreInfoConflictLabel: 'Conflict-free',
    scoreInfoConflictTip: 'A conflict is two classes landing on the same day and time slot. Zero conflicts gives 35 points; each conflict removes 12 (floored at 0).',
    scoreInfoCoverageLabel: 'Course coverage',
    scoreInfoCoverageTip: 'Every valid schedule that fully includes all selected courses earns 25 points.',
    scoreInfoEctsLabel: 'Total ECTS',
    scoreInfoEctsTip: 'European Credit Transfer System credits. Does not affect the score; shown separately for information.',
    scoreInfoFreeDaysTermLabel: 'Free-day bonus',
    scoreInfoFreeDaysTip: 'Each fully free weekday adds +7 (up to 20) — more free days, higher score.',
    scoreInfoGapsLabel: 'Compactness',
    scoreInfoGapsTip: 'Up to 20 points; each idle hour between classes removes 4 — a more compact (gap-free) schedule scores higher.',
    scoreInfoTotal: 'Total score',
    scoreInfoFootnote: 'The score is out of 100: conflict-free schedules with more free days and fewer gaps score higher.',
    scoreInfoHoldHint: 'Hold to pin',
    scoreInfoLockedHint: 'Pinned — hover the terms',
    scoreInfoClose: 'Close',
    resultsPhoneTitle: 'Send to your phone',
    resultsPhoneDesc: 'Scan the QR code and carry your schedule everywhere.',
    resultsExportIcs: 'Add to calendar (.ics)',
    resultsPrintPdf: 'Print / PDF',
    resultsShare: 'Share schedule',
    resultsCopy: 'Copy link',
    resultsCopied: 'Link copied',
    resultsViewAll: 'View schedules',
    pickCoursesHint: 'Pick courses to get started.',
    restoredSession: 'Your last workspace was restored.',
    selectionReset: 'Selected courses were cleared.',
    locksReset: 'All locks were cleared.',
    selectionMayConflict: 'The selected section may still conflict with your current draft.',
    unavailableCoursesSkipped: 'Some saved selections were not available in the new data source.',
    prerequisiteWarning: 'Missing prerequisites for selected course:',
    corequisiteWarning: 'Missing corequisites for selected course:',
    missingPreCoWarning: 'Missing Prerequisites/Corequisites',
    undo: 'Undo',
    redo: 'Redo',
    nothingToUndo: 'Nothing to undo.',
    nothingToRedo: 'Nothing to redo.',
    undone: 'Reverted the last change.',
    redone: 'Reapplied the change.',
    exportMenu: 'Export',
    exportIcal: 'Download calendar (.ics)',
    exportPrint: 'Print / Save as PDF',
    exportIcalDone: 'Calendar file ready.',
    exportNothingToExport: 'No courses to export yet.',
    instructor: 'Instructor',
    allInstructors: 'All instructors',
    clearSearch: 'Clear search',
    stats: 'Statistics',
    statsFreeDays: 'Free days',
    statsFreeDay: 'Free day',
    statsBusyDays: 'Busy days',
    statsTotalHours: 'Class hours',
    statsGaps: 'Idle hours',
    statsFirstClass: 'First class',
    statsLastClass: 'Last class',
    statsNoClass: 'No classes',
    confirmClearSelectionTitle: 'Clear every course?',
    confirmClearSelectionMessage: 'All selected courses will be removed from your draft.',
    confirmClearLocksTitle: 'Remove every lock?',
    confirmClearLocksMessage: 'All locked slots will be unlocked.',
    confirmYes: 'Yes, continue',
    confirmCancel: 'Cancel',
    keyboardShortcuts: 'Keyboard shortcuts',
    shortcutUndo: 'Undo the last change',
    shortcutRedo: 'Redo the last change',
    shortcutPrevSchedule: 'Previous schedule',
    shortcutNextSchedule: 'Next schedule',
    shortcutGenerate: 'Generate schedule',
    shortcutToggleHelp: 'Open or close this panel',
    shortcutCloseModal: 'Close the open dialog',
    shortcutFocusSearch: 'Focus the course search',
    shortcutExport: 'Open export menu',
    navScheduler: 'Scheduler',
    navUpload: 'Upload',
    navAdmin: 'Admin',
    navLogin: 'Log in',
    navLogout: 'Log out',
    close: 'Close',
    closeDialog: 'Close dialog',
    redirectTitle: 'Redirecting to Scheduler',
    redirectDescription: 'This legacy flow now opens the main scheduler experience.',
    schedulerNoActiveTitle: 'No active semester found',
    schedulerNoActiveDescription: 'There is no global course semester yet. Upload a .xlsx course file to continue.',
    schedulerOpenCourseDrawer: 'Courses',
    schedulerCoursesDrawerTitle: 'Courses',
    schedulerMobileDaySchedule: 'Daily schedule',
    schedulerNoCoursesForDay: 'No classes for this day.',
    schedulerEmptySlot: 'Free slot',
    schedulerPreferences: 'Preferences',
    schedulerEarliest: 'Earliest class',
    schedulerLatest: 'Latest class',
    schedulerDaysOff: 'Preferred days off',
    schedulerGapPref: 'Gap preference',
    schedulerGapCompact: 'Compact',
    schedulerGapBalanced: 'Balanced',
    schedulerGapSpread: 'Spread',
    schedulerSelectedTitle: 'Selected courses',
    schedulerNoSelectionHint: 'Selected courses will appear here.',
    schedulerCoursesTitle: 'Courses',
    schedulerBuildTitle: 'Build',
    schedulerShowCourses: 'Show course list',
    schedulerHideCourses: 'Hide course list',
    schedulerShowBuild: 'Show build panel',
    schedulerHideBuild: 'Hide build panel',
    schedulerBlockedTimes: 'Blocked times',
    schedulerNoBlockedTitle: 'No blocked times',
    schedulerNoBlockedDescription: 'Use the lock button on any empty or occupied schedule cell to keep that time unavailable.',
    schedulerUnblockTime: 'Unblock time',
    schedulerEctsBudget: 'ECTS budget',
    schedulerEctsRemaining: 'ECTS available',
    schedulerEctsOver: 'ECTS over budget',
    schedulerEctsFull: 'ECTS budget full',
    schedulerClassWindow: 'Class window',
    schedulerConflictHelp: 'The maximum number of overlapping class blocks allowed while generating schedules. Set it to 0 to require a clash-free schedule.',
    schedulerGapHelp: 'Controls idle time between classes. Compact packs classes together, Balanced leaves short breaks, and Spread allows wider gaps.',
    schedulerShareSchedule: 'Share Schedule',
    schedulerShareAction: 'Share Schedule (Link & QR)',
    schedulerShareDescription: 'Scan this QR code or use the link below to access your shared schedule.',
    schedulerCopyLink: 'Copy',
    schedulerShareCopied: 'Link copied.',
    schedulerShareFailed: 'Failed to share schedule.',
    schedulerShareCodeFailed: 'Failed to generate code.',
    schedulerGeneratedCount: 'schedules generated.',
    schedulerSelectedAlternative: 'Selected',
    adminPanel: 'Admin Panel',
    adminRole: 'ADMIN',
    adminNewSemester: 'Upload New Semester',
    adminNewSemesterDesc: 'Upload an Excel file and make it available to everyone.',
    adminSemesterName: 'Semester Name',
    adminExcelFile: 'Excel File',
    adminChooseExcel: 'Choose Excel',
    adminUploading: 'Uploading...',
    adminSemesters: 'Uploaded Semesters',
    adminNoSemesters: 'No semester uploaded yet.',
    adminActivate: 'Activate',
    adminActive: 'ACTIVE',
    adminUsers: 'Users',
    adminSavedSchedules: 'Saved Schedules',
    adminCourses: 'Courses',
    adminActiveSemester: 'Active Semester',
    adminNone: 'None',
    adminUploadInvalid: 'Only .xlsx Excel files can be uploaded.',
    adminUploadSuccess: 'courses uploaded.',
    adminUploadError: 'Upload failed',
    adminActivateSuccess: 'Semester activated.',
    adminFetchError: 'Admin data could not be loaded.',
    adminActivateError: 'Semester could not be activated.',
    adminStatsLoading: 'Loading statistics...',
    adminSemestersLoading: 'Loading semesters...',
    sharedLoading: 'Loading shared schedule...',
    sharedNotFoundTitle: 'Schedule not found',
    sharedNotFoundDescription: 'This shared schedule could not be found or may have been deleted.',
    sharedReturnHome: 'Return Home',
    sharedSchedule: 'Shared Schedule',
    sharedMakeOwn: 'Make Your Own',
    sharedCourseCount: 'courses',
    sharedMobileTitle: 'Daily view',
};

const translations: Record<Language, Translations> = { tr, en };

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLang] = useState<Language>('tr');
    const [hasLoadedPreference, setHasLoadedPreference] = useState(false);

    useEffect(() => {
        try {
            const saved = localStorage.getItem('isikschedule:lang') as Language | null;
            if (saved === 'tr' || saved === 'en') {
                setLang(saved);
                document.documentElement.lang = saved;
            }
        } catch {
            // Ignore storage access errors.
        } finally {
            setHasLoadedPreference(true);
        }
    }, []);

    useEffect(() => {
        if (!hasLoadedPreference) return;
        document.documentElement.lang = lang;
        try {
            localStorage.setItem('isikschedule:lang', lang);
        } catch {
            // Ignore storage access errors.
        }
    }, [hasLoadedPreference, lang]);

    return (
        <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}

export function LanguageSwitcher() {
    const { lang, setLang } = useLanguage();

    return (
        <div className="flex items-center bg-surface-700/50 rounded-lg p-0.5 border border-white/5">
            <button
                type="button"
                onClick={() => setLang('tr')}
                aria-label="Türkçe"
                className={`px-2.5 py-1.5 rounded-md text-xs font-medium transition-all duration-150 ${
                    lang === 'tr'
                        ? 'bg-isik-blue-lighter/20 text-isik-blue-lighter shadow-sm'
                        : 'text-slate-400 hover:text-slate-200'
                }`}
                title="Türkçe"
            >
                TR
            </button>
            <button
                type="button"
                onClick={() => setLang('en')}
                aria-label="English"
                className={`px-2.5 py-1.5 rounded-md text-xs font-medium transition-all duration-150 ${
                    lang === 'en'
                        ? 'bg-isik-blue-lighter/20 text-isik-blue-lighter shadow-sm'
                        : 'text-slate-400 hover:text-slate-200'
                }`}
                title="English"
            >
                EN
            </button>
        </div>
    );
}
